blank_issues_enabled: false
contact_links:
  - name: Lemonade Discord
    url: https://discord.gg/NVTYcV4v2Q
    about: If you are experiencing an issue with Lemonade, and you need tech support, or if you have a general question, try asking in the official Lemonade Discord linked here. Piracy is not allowed.
